/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \version 6.9.3
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2023 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains the generated Rte source code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.9.3
 * on Tue Mar 26 17:32:03 IST 2024. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#ifndef RTE_CORE
#define RTE_CORE
#endif
#include <Rte_Intern.h>
#include <Rte_Main.h>
#include <Rte_BswM.h>
#include <Rte_ComM.h>
#include <Rte_DevelopmentErrorTracer.h>
#include <Rte_SWC_ModifyEcho.h>
#include <Rte_SWC_CyclicCounter.h>
#include <Rte_SWC_IoHwAbs.h>
#include <Rte_NvMData.h>
#include <SchM_Port.h>
#include <SchM_Mcu.h>
#include <SchM_EcuM.h>
#include <SchM_Dio.h>
#include <SchM_Det.h>
#include <SchM_Dem.h>
#include <SchM_Com.h>
#include <SchM_ComM.h>
#include <SchM_Can.h>
#include <SchM_CanSM.h>
#include <SchM_CanIf.h>
#include <SchM_BswM.h>
#include <Rte_Hook.h>

/* ==================[Declaration of functions with internal linkage]========= */
STATIC FUNC(void, RTE_CODE) Rte_Common_Init (void);

/* ==================[Definition of constants with internal linkage]========== */
#define RTE_START_SEC_CONST_8
#include <Rte_MemMap.h>
STATIC CONST(uint8, RTE_CONST) Init_Rte_Irv_SWC_CyclicCounter_CurrentCounterValue = 0U;
STATIC CONST(uint8, RTE_CONST) Init_Rte_ReceiveBuffer_4061E26959A98B41A8F9EF551DBA37CE_value = 0U;
STATIC CONST(uint8, RTE_CONST) Init_Rte_ModeVariable_CB17E928A5383182DDEB81D870E37CAB = RTE_TRANSITION_BswM_BSWM_BswMModeGroup;
#define RTE_STOP_SEC_CONST_8
#include <Rte_MemMap.h>

/* ==================[Definition of variables with internal linkage]========== */
#define RTE_START_SEC_CONST_8
#include <Rte_MemMap.h>
STATIC CONST(uint8, RTE_CONST) Rte_Prm_SWC_CyclicCounter_Inst_PrmCounterValue = 99U;
#define RTE_STOP_SEC_CONST_8
#include <Rte_MemMap.h>
#define RTE_START_SEC_VAR_INIT_8
#include <Rte_MemMap.h>
STATIC VAR(uint8, RTE_VAR) Rte_State = RTE_PARTITION_UNINITIALIZED;
STATIC VAR(uint8, RTE_VAR) SchM_State = SCHM_PARTITION_UNINITIALIZED;
#define RTE_STOP_SEC_VAR_INIT_8
#include <Rte_MemMap.h>
#define RTE_START_SEC_VAR_CLEARED_8
#include <Rte_MemMap.h>
STATIC VAR(Rte_DE_uint8, RTE_VAR) Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770; /* Rte_DataHandleBuffer__SWC_ModifyEcho_P_EchoOut_CounterValue */
STATIC VAR(Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6_Type, RTE_VAR) Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6; /* Rte_ReceiveQueue__SWC_CyclicCounter_R_SpecialHandling_EventMessage */
STATIC VAR(Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_Type, RTE_VAR) Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB; /* Rte_ModeReceiveQueue__BswM_Prototype_BswM_ModeSwitchPort_BswMSwitchPort_Rte_CurrentMode */
#define RTE_STOP_SEC_VAR_CLEARED_8
#include <Rte_MemMap.h>

/* ==================[Definition of constants with external linkage]========== */
#define RTE_START_SEC_CONST_32
#include <Rte_MemMap.h>
CONST(Rte_CDS_SWC_ModifyEcho, RTE_CONST) Rte_Instance_SWC_ModifyEcho = 
{
  &Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770
};
CONST(Rte_CDS_SWC_CyclicCounter, RTE_CONST) Rte_Instance_SWC_CyclicCounter = 
{
  &Rte_Pim_SWC_CyclicCounter_PimCounterValue
};
#define RTE_STOP_SEC_CONST_32
#include <Rte_MemMap.h>
#define RTE_START_SEC_CONST_8
#include <Rte_MemMap.h>
CONST(Rte_CDS_BswM, RTE_CONST) Rte_Instance_BswM = 
{
  /* dummy entry */
  0U
};
CONST(Rte_CDS_ComM, RTE_CONST) Rte_Instance_ComM = 
{
  /* dummy entry */
  0U
};
CONST(Rte_CDS_DevelopmentErrorTracer, RTE_CONST) Rte_Instance_DevelopmentErrorTracer = 
{
  /* dummy entry */
  0U
};
CONST(Rte_CDS_SWC_IoHwAbs, RTE_CONST) Rte_Instance_SWC_IoHwAbs = 
{
  /* dummy entry */
  0U
};
#define RTE_STOP_SEC_CONST_8
#include <Rte_MemMap.h>
#define RTE_START_SEC_CONST_32
#include <Rte_MemMap.h>
CONSTP2CONST(Rte_CDS_BswM, RTE_CONST, RTE_CONST) Rte_Inst_BswM = &Rte_Instance_BswM;
CONSTP2CONST(Rte_CDS_ComM, RTE_CONST, RTE_CONST) Rte_Inst_ComM = &Rte_Instance_ComM;
CONSTP2CONST(Rte_CDS_DevelopmentErrorTracer, RTE_CONST, RTE_CONST) Rte_Inst_DevelopmentErrorTracer = &Rte_Instance_DevelopmentErrorTracer;
CONSTP2CONST(Rte_CDS_SWC_ModifyEcho, RTE_CONST, RTE_CONST) Rte_Inst_SWC_ModifyEcho = &Rte_Instance_SWC_ModifyEcho;
CONSTP2CONST(Rte_CDS_SWC_CyclicCounter, RTE_CONST, RTE_CONST) Rte_Inst_SWC_CyclicCounter = &Rte_Instance_SWC_CyclicCounter;
CONSTP2CONST(Rte_CDS_SWC_IoHwAbs, RTE_CONST, RTE_CONST) Rte_Inst_SWC_IoHwAbs = &Rte_Instance_SWC_IoHwAbs;
#define RTE_STOP_SEC_CONST_32
#include <Rte_MemMap.h>

/* ==================[Definition of variables with external linkage]========== */
#define RTE_START_SEC_VAR_CLEARED_8
#include <Rte_MemMap.h>
VAR(uint8, RTE_VAR) Rte_Irv_SWC_CyclicCounter_CurrentCounterValue;
VAR(uint8, RTE_VAR) Rte_ReceiveBuffer_4061E26959A98B41A8F9EF551DBA37CE_value; /* Rte_ReceiveBuffer__SWC_ModifyEcho_R_NewCounterIn_CounterValue */
VAR(uint8, RTE_VAR) Rte_ModeVariable_CB17E928A5383182DDEB81D870E37CAB; /* Rte_ModeVariable__BswM_Prototype_BswM_ModeSwitchPort_BswMSwitchPort_Rte_CurrentMode */
VAR(Rte_ModeDisablingDep_Type, RTE_VAR) Rte_ModeDisablingDep;
#define RTE_STOP_SEC_VAR_CLEARED_8
#include <Rte_MemMap.h>
#define RTE_START_SEC_VAR_INIT_UNSPECIFIED
#include <Rte_MemMap.h>
VAR(Rte_PimType_SWC_CyclicCounter_CounterValueType, RTE_VAR) Rte_Pim_SWC_CyclicCounter_PimCounterValue = 99;
#define RTE_STOP_SEC_VAR_INIT_UNSPECIFIED
#include <Rte_MemMap.h>

/* ==================[Definition of functions with external linkage]========== */
#define RTE_START_SEC_CODE
#include <Rte_MemMap.h>
FUNC(Std_ReturnType, RTE_CODE) Rte_Switch_BswM_BswM_ModeSwitchPort_BswMSwitchPort_Rte_CurrentMode (uint8 mode)
{
  Std_ReturnType Rte_Status = RTE_E_OK;

  Rte_SwitchHook_BswM_BswM_ModeSwitchPort_BswMSwitchPort_Rte_CurrentMode_Start(mode);

  if (Rte_State == RTE_PARTITION_ACTIVE)
  {
    {
      Std_ReturnType Rte_QueueStatus = RTE_E_OK;
      uint8 Rte_Local_Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_head = Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.head;

      if (Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.tail == ((Rte_Local_Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_head + 1U) % 2U))
      {
        Rte_QueueStatus = RTE_E_LIMIT;
      }
      else
      {
        uint8 Rte_Local_Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_tailIdx = Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.tail % 1U;

        Atomics_ThreadFence();
        Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.queue[Rte_Local_Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_tailIdx] = mode;
        Atomics_ThreadFence();
        Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.tail = ((Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.tail + 1U) % 2U);
      }
      if (Rte_QueueStatus != RTE_E_OK)
      {
        Rte_Status = RTE_E_LIMIT;
      }
      else
      {
        Rte_SetEvent_MSE_4FF9241E67DF8B0AADC83685D425BB32();

      }
    }
  }

  Rte_SwitchHook_BswM_BswM_ModeSwitchPort_BswMSwitchPort_Rte_CurrentMode_Return(mode);
  return Rte_Status;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Switch_BswM_BswM_ModeSwitchPort_BswMSwitchPort_Rte_CurrentMode (uint8 mode) */

FUNC(Std_ReturnType, RTE_CODE) Rte_Switch_ComM_UM_ComMUser_0_currentMode (uint8 mode)
{
  Rte_SwitchHook_ComM_UM_ComMUser_0_currentMode_Start(mode);

  Rte_SwitchHook_ComM_UM_ComMUser_0_currentMode_Return(mode);
  TS_PARAM_UNUSED(mode);
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Switch_ComM_UM_ComMUser_0_currentMode (uint8 mode) */

FUNC(Std_ReturnType, RTE_CODE) Rte_Send_SWC_ModifyEcho_P_SpecialRequest_EventMessage (uint8 data)
{
  Std_ReturnType Rte_Status = RTE_E_OK;
  Std_ReturnType Rte_QueueStatus = RTE_E_OK;

  Rte_SendHook_SWC_ModifyEcho_P_SpecialRequest_EventMessage_Start(data);
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {
    uint8 Rte_Local_Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6_head = Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.head;

    if (Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.tail == ((Rte_Local_Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6_head + 8U) % 16U))
    {
      Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.ldcWriter++;
      Rte_QueueStatus = RTE_E_LIMIT;
    }
    else
    {
      uint8 Rte_Local_Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6_tailIdx = Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.tail % 8U;

      Atomics_ThreadFence();
      Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.queue[Rte_Local_Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6_tailIdx] = data;
      Atomics_ThreadFence();
      Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.tail = ((Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.tail + 1U) % 16U);
    }
    if (Rte_QueueStatus == RTE_E_LIMIT)
    {
      Rte_Status = RTE_E_LIMIT;
    }
  }

  Rte_SendHook_SWC_ModifyEcho_P_SpecialRequest_EventMessage_Return(data);
  return Rte_Status;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Send_SWC_ModifyEcho_P_SpecialRequest_EventMessage (uint8 data) */

FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_ModifyEcho_R_NewCounterIn_CounterValue (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
{
  Std_ReturnType Rte_Status = RTE_E_OK;

  Rte_ReadHook_SWC_ModifyEcho_R_NewCounterIn_CounterValue_Start(data);
  *data = Rte_ReceiveBuffer_4061E26959A98B41A8F9EF551DBA37CE_value;

  Rte_ReadHook_SWC_ModifyEcho_R_NewCounterIn_CounterValue_Return(data);
  return Rte_Status;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_ModifyEcho_R_NewCounterIn_CounterValue (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data) */

FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_ModifyEcho_R_EchoResult_SetCounterAndAdd (uint8 newCounterValue, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) returnSum)
{
  Std_ReturnType Rte_Status = RTE_E_OK;

  Rte_CallHook_SWC_ModifyEcho_R_EchoResult_SetCounterAndAdd_Start(newCounterValue, returnSum);
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {

    /* RunnableEntity SetCounter */
    Rte_Runnable_SWC_CyclicCounter_SetCounter_Start();
    SWC_CyclicCounter_SetCounter(newCounterValue, returnSum);
    Rte_Runnable_SWC_CyclicCounter_SetCounter_Return();

  }
  else
  {
    Rte_Status = RTE_E_TIMEOUT;
  }

  Rte_CallHook_SWC_ModifyEcho_R_EchoResult_SetCounterAndAdd_Return(newCounterValue, returnSum);
  return Rte_Status;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_ModifyEcho_R_EchoResult_SetCounterAndAdd (uint8 newCounterValue, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) returnSum) */

FUNC(uint8, RTE_CODE) Rte_IrvRead_SWC_CyclicCounter_SetCounter_CurrentCounterValue (void)
{
  uint8 Rte_InternalBuffer;

  Rte_IrvReadHook_SWC_CyclicCounter_SetCounter_CurrentCounterValue_Start();
  Rte_InternalBuffer = Rte_Irv_SWC_CyclicCounter_CurrentCounterValue;

  Rte_IrvReadHook_SWC_CyclicCounter_SetCounter_CurrentCounterValue_Return();
  return Rte_InternalBuffer;
} /* FUNC(uint8, RTE_CODE) Rte_IrvRead_SWC_CyclicCounter_SetCounter_CurrentCounterValue (void) */

FUNC(void, RTE_CODE) Rte_IrvWrite_SWC_CyclicCounter_SetCounter_CurrentCounterValue (uint8 data)
{
  Rte_IrvWriteHook_SWC_CyclicCounter_SetCounter_CurrentCounterValue_Start(data);
  Rte_Irv_SWC_CyclicCounter_CurrentCounterValue = data;

  Rte_IrvWriteHook_SWC_CyclicCounter_SetCounter_CurrentCounterValue_Return(data);

} /* FUNC(void, RTE_CODE) Rte_IrvWrite_SWC_CyclicCounter_SetCounter_CurrentCounterValue (uint8 data) */

FUNC(uint8, RTE_CODE) Rte_IrvRead_SWC_CyclicCounter_Cyclic_CurrentCounterValue (void)
{
  uint8 Rte_InternalBuffer;

  Rte_IrvReadHook_SWC_CyclicCounter_Cyclic_CurrentCounterValue_Start();
  Rte_InternalBuffer = Rte_Irv_SWC_CyclicCounter_CurrentCounterValue;

  Rte_IrvReadHook_SWC_CyclicCounter_Cyclic_CurrentCounterValue_Return();
  return Rte_InternalBuffer;
} /* FUNC(uint8, RTE_CODE) Rte_IrvRead_SWC_CyclicCounter_Cyclic_CurrentCounterValue (void) */

FUNC(void, RTE_CODE) Rte_IrvWrite_SWC_CyclicCounter_Cyclic_CurrentCounterValue (uint8 data)
{
  Rte_IrvWriteHook_SWC_CyclicCounter_Cyclic_CurrentCounterValue_Start(data);
  Rte_Irv_SWC_CyclicCounter_CurrentCounterValue = data;

  Rte_IrvWriteHook_SWC_CyclicCounter_Cyclic_CurrentCounterValue_Return(data);

} /* FUNC(void, RTE_CODE) Rte_IrvWrite_SWC_CyclicCounter_Cyclic_CurrentCounterValue (uint8 data) */

FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_CyclicCounter_P_CounterOut_CounterValue (uint8 data)
{
  Std_ReturnType Rte_Status = RTE_E_OK;

  Rte_WriteHook_SWC_CyclicCounter_P_CounterOut_CounterValue_Start(data);
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {
    Rte_ComHook_SGModeChangeRequest_1027T_SigTx(&data);
    if (Com_SendSignal(ComConf_ComSignal_SGModeChangeRequest_1027T, &data) != E_OK)
    {
      Rte_Status = RTE_E_COM_STOPPED;
    }
    (void) GetResource(Rte_Res_0);
    {
      Rte_ComHook_SGMotorOnOffRequest_1027T_SigTx(&data);
      if (Com_SendSignal(ComConf_ComSignal_SGMotorOnOffRequest_1027T, &data) != E_OK)
      {
        Rte_Status = RTE_E_COM_STOPPED;
      }
    }
    (void) ReleaseResource(Rte_Res_0);
    (void) GetResource(Rte_Res_1);
    {
      Rte_ComHook_SGHornOutput_1026T_SigTx(&data);
      if (Com_SendSignal(ComConf_ComSignal_SGHornOutput_1026T, &data) != E_OK)
      {
        Rte_Status = RTE_E_COM_STOPPED;
      }
    }
    (void) ReleaseResource(Rte_Res_1);
    (void) GetResource(Rte_Res_2);
    {
      Rte_ComHook_SGHighBeamOutput_1026T_SigTx(&data);
      if (Com_SendSignal(ComConf_ComSignal_SGHighBeamOutput_1026T, &data) != E_OK)
      {
        Rte_Status = RTE_E_COM_STOPPED;
      }
    }
    (void) ReleaseResource(Rte_Res_2);
    (void) GetResource(Rte_Res_3);
    {
      Rte_ComHook_SGLeftIndicatorOutput_1026T_SigTx(&data);
      if (Com_SendSignal(ComConf_ComSignal_SGLeftIndicatorOutput_1026T, &data) != E_OK)
      {
        Rte_Status = RTE_E_COM_STOPPED;
      }
    }
    (void) ReleaseResource(Rte_Res_3);
    (void) GetResource(Rte_Res_4);
    {
      Rte_ComHook_SGRightIndicatorOutput_1026T_SigTx(&data);
      if (Com_SendSignal(ComConf_ComSignal_SGRightIndicatorOutput_1026T, &data) != E_OK)
      {
        Rte_Status = RTE_E_COM_STOPPED;
      }
    }
    (void) ReleaseResource(Rte_Res_4);
    (void) GetResource(Rte_Res_5);
    {
      Rte_ComHook_SGTailLampDutyCycle_1026T_SigTx(&data);
      if (Com_SendSignal(ComConf_ComSignal_SGTailLampDutyCycle_1026T, &data) != E_OK)
      {
        Rte_Status = RTE_E_COM_STOPPED;
      }
    }
    (void) ReleaseResource(Rte_Res_5);
  }

  Rte_WriteHook_SWC_CyclicCounter_P_CounterOut_CounterValue_Return(data);
  return Rte_Status;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_CyclicCounter_P_CounterOut_CounterValue (uint8 data) */

FUNC(Std_ReturnType, RTE_CODE) Rte_Receive_SWC_CyclicCounter_R_SpecialHandling_EventMessage (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
{
  Std_ReturnType Rte_Status = RTE_E_OK;
  uint8 Rte_Local_Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6_tail = Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.tail;

  Rte_ReceiveHook_SWC_CyclicCounter_R_SpecialHandling_EventMessage_Start(data);
  if (Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.head == Rte_Local_Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6_tail)
  {
    Rte_Status = RTE_E_NO_DATA;
  }
  else
  {
    uint8 Rte_Local_Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6_headIdx = Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.head % 8U;

    if (Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.ldcReader != Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.ldcWriter)
    {
      Rte_Status |= RTE_E_LOST_DATA;
      Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.ldcReader = Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.ldcWriter;
    }
    Atomics_ThreadFence();
    *data = Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.queue[Rte_Local_Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6_headIdx];
    Atomics_ThreadFence();
    Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.head = ((Rte_ReceiveQueue_17118CBFA9C49A3FE48286291D0616C6.head + 1U) % 16U);
  }

  Rte_ReceiveHook_SWC_CyclicCounter_R_SpecialHandling_EventMessage_Return(data);
  return Rte_Status;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Receive_SWC_CyclicCounter_R_SpecialHandling_EventMessage (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data) */

FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_CyclicCounter_R_MyLED_SetDiscreteValue (uint32 value)
{
  Std_ReturnType Rte_Status = RTE_E_OK;

  Rte_CallHook_SWC_CyclicCounter_R_MyLED_SetDiscreteValue_Start(value);
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {

    /* RunnableEntity SetDiscreteValue */
    Rte_Runnable_SWC_IoHwAbs_SetDiscreteValue_Start();
    SWC_IoHwAbs_SetDiscreteValue(0U, value);
    Rte_Runnable_SWC_IoHwAbs_SetDiscreteValue_Return();

  }
  else
  {
    Rte_Status = RTE_E_TIMEOUT;
  }

  Rte_CallHook_SWC_CyclicCounter_R_MyLED_SetDiscreteValue_Return(value);
  return Rte_Status;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_CyclicCounter_R_MyLED_SetDiscreteValue (uint32 value) */

FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_CyclicCounter_R_CyclicCounterDet_ReportError (uint8 InstanceId, uint8 ApiId, uint8 ErrorId)
{
  Std_ReturnType Rte_Status = RTE_E_OK;

  Rte_CallHook_SWC_CyclicCounter_R_CyclicCounterDet_ReportError_Start(InstanceId, ApiId, ErrorId);
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {

    /* RunnableEntity RE_ReportError */
    Rte_Runnable_DevelopmentErrorTracer_RE_ReportError_Start();
    Rte_Status = Det_Rte_ReportError(256U, InstanceId, ApiId, ErrorId);
    Rte_Runnable_DevelopmentErrorTracer_RE_ReportError_Return();

  }
  else
  {
    Rte_Status = RTE_E_TIMEOUT;
  }

  Rte_CallHook_SWC_CyclicCounter_R_CyclicCounterDet_ReportError_Return(InstanceId, ApiId, ErrorId);
  return Rte_Status;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_CyclicCounter_R_CyclicCounterDet_ReportError (uint8 InstanceId, uint8 ApiId, uint8 ErrorId) */

FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_CyclicCounter_UR_ComMUser_0_RequestComMode (ComM_ModeType ComMode)
{
  Std_ReturnType Rte_Status = RTE_E_OK;

  Rte_CallHook_SWC_CyclicCounter_UR_ComMUser_0_RequestComMode_Start(ComMode);
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {

    /* RunnableEntity RE_RequestComMode */
    Rte_Runnable_ComM_RE_RequestComMode_Start();
    Rte_Status = ComM_Rte_RequestComMode(0U, ComMode);
    Rte_Runnable_ComM_RE_RequestComMode_Return();

  }
  else
  {
    Rte_Status = RTE_E_TIMEOUT;
  }

  Rte_CallHook_SWC_CyclicCounter_UR_ComMUser_0_RequestComMode_Return(ComMode);
  return Rte_Status;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_CyclicCounter_UR_ComMUser_0_RequestComMode (ComM_ModeType ComMode) */

FUNC(void, RTE_CODE) Rte_IrvWrite_SWC_CyclicCounter_Init_CurrentCounterValue (uint8 data)
{
  Rte_IrvWriteHook_SWC_CyclicCounter_Init_CurrentCounterValue_Start(data);
  Rte_Irv_SWC_CyclicCounter_CurrentCounterValue = data;

  Rte_IrvWriteHook_SWC_CyclicCounter_Init_CurrentCounterValue_Return(data);

} /* FUNC(void, RTE_CODE) Rte_IrvWrite_SWC_CyclicCounter_Init_CurrentCounterValue (uint8 data) */

FUNC(uint8, RTE_CODE) Rte_CData_SWC_CyclicCounter_PrmCounterValue (void)
{
  Rte_CDataHook_SWC_CyclicCounter_PrmCounterValue_Start();

  Rte_CDataHook_SWC_CyclicCounter_PrmCounterValue_Return();
  return Rte_Prm_SWC_CyclicCounter_Inst_PrmCounterValue;
} /* FUNC(uint8, RTE_CODE) Rte_CData_SWC_CyclicCounter_PrmCounterValue (void) */

FUNC(uint8, RTE_CODE) Rte_IrvRead_SWC_CyclicCounter_Shutdown_CurrentCounterValue (void)
{
  uint8 Rte_InternalBuffer;

  Rte_IrvReadHook_SWC_CyclicCounter_Shutdown_CurrentCounterValue_Start();
  Rte_InternalBuffer = Rte_Irv_SWC_CyclicCounter_CurrentCounterValue;

  Rte_IrvReadHook_SWC_CyclicCounter_Shutdown_CurrentCounterValue_Return();
  return Rte_InternalBuffer;
} /* FUNC(uint8, RTE_CODE) Rte_IrvRead_SWC_CyclicCounter_Shutdown_CurrentCounterValue (void) */

FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_CyclicCounter_PS_PersistentCounterValue_SetRamBlockStatus (boolean BlockChanged)
{
  Rte_CallHook_SWC_CyclicCounter_PS_PersistentCounterValue_SetRamBlockStatus_Start(BlockChanged);

  Rte_CallHook_SWC_CyclicCounter_PS_PersistentCounterValue_SetRamBlockStatus_Return(BlockChanged);
  TS_PARAM_UNUSED(BlockChanged);
  return RTE_E_UNCONNECTED;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_CyclicCounter_PS_PersistentCounterValue_SetRamBlockStatus (boolean BlockChanged) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_00 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_00 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_00 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_00 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_01 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_01 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_01 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_01 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_02 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_02 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_02 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_02 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_03 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_03 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_03 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_03 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_04 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_04 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_04 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_04 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_05 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_05 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_05 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_05 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_06 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_06 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_06 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_06 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_07 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_07 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_07 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_07 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_08 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_08 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_08 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_08 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_09 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_09 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_09 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_09 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_10 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_10 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_10 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_10 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_11 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_11 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_11 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_11 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_12 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_12 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_12 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_12 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_13 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_13 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_13 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_13 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_14 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_14 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_14 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_14 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_15 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_15 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_15 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_15 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_16 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_16 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_16 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_16 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_17 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_17 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_17 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_17 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_18 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_18 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_18 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_18 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_19 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_19 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_19 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_19 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_20 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_20 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_20 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_20 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_21 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_21 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_21 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_21 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_22 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_22 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_22 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_22 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_23 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_23 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_23 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_23 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_24 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_24 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_24 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_24 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_25 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_25 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_25 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_25 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_26 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_26 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_26 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_26 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_27 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_27 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_27 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_27 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Mcu_MCU_EXCLUSIVE_AREA_00 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Mcu_MCU_EXCLUSIVE_AREA_00 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Mcu_MCU_EXCLUSIVE_AREA_00 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Mcu_MCU_EXCLUSIVE_AREA_00 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Mcu_MCU_EXCLUSIVE_AREA_01 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Mcu_MCU_EXCLUSIVE_AREA_01 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Mcu_MCU_EXCLUSIVE_AREA_01 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Mcu_MCU_EXCLUSIVE_AREA_01 (void) */

FUNC(void, RTE_CODE) SchM_Enter_EcuM_SCHM_ECUM_EXCLUSIVE_AREA_0 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_EcuM_SCHM_ECUM_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Exit_EcuM_SCHM_ECUM_EXCLUSIVE_AREA_0 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_EcuM_SCHM_ECUM_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Dio_DIO_EXCLUSIVE_AREA_00 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Dio_DIO_EXCLUSIVE_AREA_00 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Dio_DIO_EXCLUSIVE_AREA_00 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Dio_DIO_EXCLUSIVE_AREA_00 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Det_SCHM_DET_EXCLUSIVE_AREA_0 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Det_SCHM_DET_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Det_SCHM_DET_EXCLUSIVE_AREA_0 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Det_SCHM_DET_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Dem_SCHM_DEM_EXCLUSIVE_AREA_0 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Dem_SCHM_DEM_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Dem_SCHM_DEM_EXCLUSIVE_AREA_0 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Dem_SCHM_DEM_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Com_SCHM_COM_EXCLUSIVE_AREA_0 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Com_SCHM_COM_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Com_SCHM_COM_EXCLUSIVE_AREA_0 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Com_SCHM_COM_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Com_SCHM_COM_EXCLUSIVE_AREA_1 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Com_SCHM_COM_EXCLUSIVE_AREA_1 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Com_SCHM_COM_EXCLUSIVE_AREA_1 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Com_SCHM_COM_EXCLUSIVE_AREA_1 (void) */

FUNC(void, RTE_CODE) SchM_Enter_ComM_SCHM_COMM_EXCLUSIVE_AREA_0 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_ComM_SCHM_COMM_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Exit_ComM_SCHM_COMM_EXCLUSIVE_AREA_0 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_ComM_SCHM_COMM_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_00 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_00 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_00 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_00 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_01 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_01 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_01 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_01 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_02 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_02 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_02 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_02 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_03 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_03 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_03 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_03 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_04 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_04 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_04 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_04 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_05 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_05 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_05 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_05 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_06 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_06 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_06 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_06 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_07 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_07 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_07 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_07 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_08 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_08 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_08 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_08 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_09 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_09 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_09 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_09 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_10 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_10 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_10 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_10 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_11 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_11 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_11 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_11 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_12 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_12 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_12 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_12 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_13 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_13 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_13 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_13 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_14 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_14 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_14 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_14 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_15 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_15 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_15 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_15 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_16 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_16 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_16 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_16 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_17 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_17 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_17 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_17 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_18 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_18 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_18 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_18 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_19 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_19 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_19 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_19 (void) */

FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_20 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_Can_CAN_EXCLUSIVE_AREA_20 (void) */

FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_20 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_Can_CAN_EXCLUSIVE_AREA_20 (void) */

FUNC(void, RTE_CODE) SchM_Enter_CanSM_SCHM_CANSM_EXCLUSIVE_AREA_0 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_CanSM_SCHM_CANSM_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Exit_CanSM_SCHM_CANSM_EXCLUSIVE_AREA_0 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_CanSM_SCHM_CANSM_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Enter_CanIf_SCHM_CANIF_EXCLUSIVE_AREA_0 (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_CanIf_SCHM_CANIF_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Exit_CanIf_SCHM_CANIF_EXCLUSIVE_AREA_0 (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_CanIf_SCHM_CANIF_EXCLUSIVE_AREA_0 (void) */

FUNC(void, RTE_CODE) SchM_Enter_BswM_SCHM_BSWM_EXCLUSIVE_AREA (void)
{
  SuspendAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Enter_BswM_SCHM_BSWM_EXCLUSIVE_AREA (void) */

FUNC(void, RTE_CODE) SchM_Exit_BswM_SCHM_BSWM_EXCLUSIVE_AREA (void)
{
  ResumeAllInterrupts();

} /* FUNC(void, RTE_CODE) SchM_Exit_BswM_SCHM_BSWM_EXCLUSIVE_AREA (void) */

TASK(SchMDiagStateTask_20ms)
{
  /* scenario A1/B1 (A1), Task priority: 50 */
  Rte_Task_Dispatch(SchMDiagStateTask_20ms);
  {

    /* BswSchedulableEntity EcuM_MainFunction */
    SchM_Schedulable_EcuM_MainFunction_Start();
    EcuM_MainFunction();
    SchM_Schedulable_EcuM_MainFunction_Return();
    /* BswSchedulableEntity BswM_MainFunction */
    SchM_Schedulable_BswM_MainFunction_Start();
    BswM_MainFunction();
    SchM_Schedulable_BswM_MainFunction_Return();
    /* BswSchedulableEntity Dem_MainFunction */
    SchM_Schedulable_Dem_MainFunction_Start();
    Dem_MainFunction();
    SchM_Schedulable_Dem_MainFunction_Return();
    /* BswSchedulableEntity ComM_MainFunction_0 */
    SchM_Schedulable_ComM_MainFunction_0_Start();
    ComM_MainFunction_0();
    SchM_Schedulable_ComM_MainFunction_0_Return();
    /* BswSchedulableEntity CanSM_MainFunction */
    SchM_Schedulable_CanSM_MainFunction_Start();
    CanSM_MainFunction();
    SchM_Schedulable_CanSM_MainFunction_Return();

  }
  Rte_Task_EndHook(SchMDiagStateTask_20ms);
  Rte_Task_Terminate(SchMDiagStateTask_20ms);
  (void)TerminateTask();

} /* TASK(SchMDiagStateTask_20ms) */

TASK(SchMComTask_5ms)
{
  /* scenario A1/B1 (A1), Task priority: 150 */
  Rte_Task_Dispatch(SchMComTask_5ms);
  {

    /* BswSchedulableEntity Com_MainFunctionRx */
    SchM_Schedulable_Com_MainFunctionRx_Start();
    Com_MainFunctionRx();
    SchM_Schedulable_Com_MainFunctionRx_Return();
    /* BswSchedulableEntity Com_MainFunctionRouteSignals */
    SchM_Schedulable_Com_MainFunctionRouteSignals_Start();
    Com_MainFunctionRouteSignals();
    SchM_Schedulable_Com_MainFunctionRouteSignals_Return();
    /* BswSchedulableEntity Com_MainFunctionTx */
    SchM_Schedulable_Com_MainFunctionTx_Start();
    Com_MainFunctionTx();
    SchM_Schedulable_Com_MainFunctionTx_Return();
    /* BswSchedulableEntity Can_MainFunction_Mode */
    SchM_Schedulable_Can_MainFunction_Mode_Start();
    Can_MainFunction_Mode();
    SchM_Schedulable_Can_MainFunction_Mode_Return();

  }
  Rte_Task_EndHook(SchMComTask_5ms);
  Rte_Task_Terminate(SchMComTask_5ms);
  (void)TerminateTask();

} /* TASK(SchMComTask_5ms) */

TASK(Rte_Event_Task)
{
  /* scenario B2, Task priority: 51 */
  EventMaskType Rte_CurrentEvent;
  boolean Rte_ShutdownFlag = FALSE;

  Rte_Task_Dispatch(Rte_Event_Task);
  while(!Rte_ShutdownFlag)
  {
    (void)Rte_WaitGetClearEvent(Rte_OSShutdownEvent | Rte_OSTriggerExecutableEvent_Rte_Event_Task_DRE_19B10114FE44DF3968D219DF6B46CFD0 | Rte_OSTriggerExecutableEvent_Rte_Event_Task_MSE_4FF9241E67DF8B0AADC83685D425BB32, &Rte_CurrentEvent, Rte_Event_Task);
    if ((Rte_CurrentEvent & Rte_OSShutdownEvent) != 0U)
    {
      /* shutdown notification arrived */
      Rte_ShutdownFlag = TRUE;
    }
    else
    {

      if ((Rte_CurrentEvent & Rte_OSTriggerExecutableEvent_Rte_Event_Task_DRE_19B10114FE44DF3968D219DF6B46CFD0) != 0U)
      {
        /* RunnableEntity ModifyEcho */
        Rte_Runnable_SWC_ModifyEcho_ModifyEcho_Start();
        SWC_ModifyEcho_ModifyEcho();
        Rte_Runnable_SWC_ModifyEcho_ModifyEcho_Return();

      }
      if ((Rte_CurrentEvent & Rte_OSTriggerExecutableEvent_Rte_Event_Task_MSE_4FF9241E67DF8B0AADC83685D425BB32) != 0U)
      {
        {
          uint8 Rte_NextMode;
          uint8 Rte_Local_Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_tail = Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.tail;
          uint8 Rte_CurrentMode;

          while(Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.head != Rte_Local_Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_tail)
          {
            uint8 Rte_Local_Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_headIdx = Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.head % 1U;
            Rte_ModeDisablingDep_Type Rte_EnabledModeDisablingDep = {0U};

            Atomics_ThreadFence();
            Rte_NextMode = Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.queue[Rte_Local_Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_headIdx];
            Atomics_ThreadFence();
            Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.head = ((Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.head + 1U) % 2U);
            Rte_CurrentMode = Rte_ModeVariable_CB17E928A5383182DDEB81D870E37CAB;

            Rte_IntLock();
            Rte_ModeVariable_CB17E928A5383182DDEB81D870E37CAB = RTE_TRANSITION_BswM_BSWM_BswMModeGroup;
            /* Enable Mode Disabling Dependencies of next mode */

            switch (Rte_NextMode)
            {
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_GO_OFF_ONE_A:
              {
                Rte_EnableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
                break;
              }
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_GO_OFF_ONE_B:
              {
                Rte_EnableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
                break;
              }
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_PRP_SHUTDOWN:
              {
                Rte_EnableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
                break;
              }
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_STARTUP_TWO_A:
              {
                Rte_EnableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
                break;
              }
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_STARTUP_TWO_B:
              {
                Rte_EnableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
                break;
              }
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_WAKEUP_TWO:
              {
                Rte_EnableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
                break;
              }
              default:
              {
                /* none */
                break;
              }
            }
            Rte_IntUnlock();

            /* trigger On Entry Executables */

            switch (Rte_NextMode)
            {
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_PRP_SHUTDOWN:
              {
                /* RunnableEntity Shutdown */
                Rte_Runnable_SWC_CyclicCounter_Shutdown_Start();
                SWC_CyclicCounter_Shutdown();
                Rte_Runnable_SWC_CyclicCounter_Shutdown_Return();

                break;
              }
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_RUN_TWO:
              {
                /* RunnableEntity Init */
                Rte_Runnable_SWC_CyclicCounter_Init_Start();
                SWC_CyclicCounter_Init();
                Rte_Runnable_SWC_CyclicCounter_Init_Return();

                break;
              }
              default:
              {
                /* none */
                break;
              }
            }
            Rte_IntLock();
            /* Disable Mode Disabling Dependencies of current mode */

            switch (Rte_CurrentMode)
            {
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_GO_OFF_ONE_A:
              {
                Rte_DisableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
                break;
              }
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_GO_OFF_ONE_B:
              {
                Rte_DisableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
                break;
              }
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_PRP_SHUTDOWN:
              {
                Rte_DisableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
                break;
              }
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_STARTUP_TWO_A:
              {
                Rte_DisableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
                break;
              }
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_STARTUP_TWO_B:
              {
                Rte_DisableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
                break;
              }
              case RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_WAKEUP_TWO:
              {
                Rte_DisableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
                break;
              }
              default:
              {
                /* none */
                break;
              }
            }
            Rte_ModeVariable_CB17E928A5383182DDEB81D870E37CAB = Rte_NextMode;

            Rte_IntUnlock();

          }
        }

      }

      /* Implicit Write Accesses */
      {

        if ((Rte_CurrentEvent & Rte_OSTriggerExecutableEvent_Rte_Event_Task_DRE_19B10114FE44DF3968D219DF6B46CFD0) != 0U)
        {

          (void) GetResource(Rte_Res_0);
          {
            Rte_ComHook_SGMotorOnOffRequest_1027T_SigTx(&Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770.value);
            (void)Com_SendSignal(ComConf_ComSignal_SGMotorOnOffRequest_1027T, &Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770.value);
          }
          (void) ReleaseResource(Rte_Res_0);
          (void) GetResource(Rte_Res_1);
          {
            Rte_ComHook_SGHornOutput_1026T_SigTx(&Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770.value);
            (void)Com_SendSignal(ComConf_ComSignal_SGHornOutput_1026T, &Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770.value);
          }
          (void) ReleaseResource(Rte_Res_1);
          (void) GetResource(Rte_Res_2);
          {
            Rte_ComHook_SGHighBeamOutput_1026T_SigTx(&Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770.value);
            (void)Com_SendSignal(ComConf_ComSignal_SGHighBeamOutput_1026T, &Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770.value);
          }
          (void) ReleaseResource(Rte_Res_2);
          (void) GetResource(Rte_Res_3);
          {
            Rte_ComHook_SGLeftIndicatorOutput_1026T_SigTx(&Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770.value);
            (void)Com_SendSignal(ComConf_ComSignal_SGLeftIndicatorOutput_1026T, &Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770.value);
          }
          (void) ReleaseResource(Rte_Res_3);
          (void) GetResource(Rte_Res_4);
          {
            Rte_ComHook_SGRightIndicatorOutput_1026T_SigTx(&Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770.value);
            (void)Com_SendSignal(ComConf_ComSignal_SGRightIndicatorOutput_1026T, &Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770.value);
          }
          (void) ReleaseResource(Rte_Res_4);
          (void) GetResource(Rte_Res_5);
          {
            Rte_ComHook_SGTailLampDutyCycle_1026T_SigTx(&Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770.value);
            (void)Com_SendSignal(ComConf_ComSignal_SGTailLampDutyCycle_1026T, &Rte_DataHandleBuffer_3A4ADA34331F3ECCFA48DD8AF22D1770.value);
          }
          (void) ReleaseResource(Rte_Res_5);
        }
      }
    }
  }

  Rte_Task_EndHook(Rte_Event_Task);
  Rte_Task_Terminate(Rte_Event_Task);
  (void)TerminateTask();

} /* TASK(Rte_Event_Task) */

TASK(Rte_Time_Task)
{
  /* scenario A1/B1 (A1), Task priority: 52 */
  Rte_Task_Dispatch(Rte_Time_Task);
  {

    if (!Rte_IsModeDisablingDepSet_0())
    {
      /* RunnableEntity Cyclic */
      Rte_Runnable_SWC_CyclicCounter_Cyclic_Start();
      SWC_CyclicCounter_Cyclic();
      Rte_Runnable_SWC_CyclicCounter_Cyclic_Return();

    }

  }
  Rte_Task_EndHook(Rte_Time_Task);
  Rte_Task_Terminate(Rte_Time_Task);
  (void)TerminateTask();

} /* TASK(Rte_Time_Task) */

FUNC(void, RTE_CODE) Rte_COMCbk_SGKeyStatus_1281R (void)
{
  uint8 Rte_InternalBuffer;

  Rte_ComHookRx_SGKeyStatus_1281R();
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {
    if (Com_ReceiveSignal(ComConf_ComSignal_SGKeyStatus_1281R, &Rte_InternalBuffer) == E_OK)
    {
      Rte_ComHook_SGKeyStatus_1281R_SigRx(&Rte_InternalBuffer);
      Rte_ReceiveBuffer_4061E26959A98B41A8F9EF551DBA37CE_value = Rte_InternalBuffer;

      Rte_SetEvent_DRE_19B10114FE44DF3968D219DF6B46CFD0();

    }
  }

} /* FUNC(void, RTE_CODE) Rte_COMCbk_SGKeyStatus_1281R (void) */

FUNC(void, RTE_CODE) Rte_COMCbk_SGKillSwitchStatus_1281R (void)
{
  uint8 Rte_InternalBuffer;

  Rte_ComHookRx_SGKillSwitchStatus_1281R();
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {
    if (Com_ReceiveSignal(ComConf_ComSignal_SGKillSwitchStatus_1281R, &Rte_InternalBuffer) == E_OK)
    {
      Rte_ComHook_SGKillSwitchStatus_1281R_SigRx(&Rte_InternalBuffer);
      Rte_ReceiveBuffer_4061E26959A98B41A8F9EF551DBA37CE_value = Rte_InternalBuffer;

      Rte_SetEvent_DRE_19B10114FE44DF3968D219DF6B46CFD0();

    }
  }

} /* FUNC(void, RTE_CODE) Rte_COMCbk_SGKillSwitchStatus_1281R (void) */

FUNC(void, RTE_CODE) Rte_COMCbk_SGSideStandStatus_1281R (void)
{
  uint8 Rte_InternalBuffer;

  Rte_ComHookRx_SGSideStandStatus_1281R();
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {
    if (Com_ReceiveSignal(ComConf_ComSignal_SGSideStandStatus_1281R, &Rte_InternalBuffer) == E_OK)
    {
      Rte_ComHook_SGSideStandStatus_1281R_SigRx(&Rte_InternalBuffer);
      Rte_ReceiveBuffer_4061E26959A98B41A8F9EF551DBA37CE_value = Rte_InternalBuffer;

      Rte_SetEvent_DRE_19B10114FE44DF3968D219DF6B46CFD0();

    }
  }

} /* FUNC(void, RTE_CODE) Rte_COMCbk_SGSideStandStatus_1281R (void) */

FUNC(void, RTE_CODE) Rte_COMCbk_SGSoC_1281R (void)
{
  uint8 Rte_InternalBuffer;

  Rte_ComHookRx_SGSoC_1281R();
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {
    if (Com_ReceiveSignal(ComConf_ComSignal_SGSoC_1281R, &Rte_InternalBuffer) == E_OK)
    {
      Rte_ComHook_SGSoC_1281R_SigRx(&Rte_InternalBuffer);
      Rte_ReceiveBuffer_4061E26959A98B41A8F9EF551DBA37CE_value = Rte_InternalBuffer;

      Rte_SetEvent_DRE_19B10114FE44DF3968D219DF6B46CFD0();

    }
  }

} /* FUNC(void, RTE_CODE) Rte_COMCbk_SGSoC_1281R (void) */

FUNC(void, RTE_CODE) Rte_COMCbk_SGMotorTemp_1281R (void)
{
  uint8 Rte_InternalBuffer;

  Rte_ComHookRx_SGMotorTemp_1281R();
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {
    if (Com_ReceiveSignal(ComConf_ComSignal_SGMotorTemp_1281R, &Rte_InternalBuffer) == E_OK)
    {
      Rte_ComHook_SGMotorTemp_1281R_SigRx(&Rte_InternalBuffer);
      Rte_ReceiveBuffer_4061E26959A98B41A8F9EF551DBA37CE_value = Rte_InternalBuffer;

      Rte_SetEvent_DRE_19B10114FE44DF3968D219DF6B46CFD0();

    }
  }

} /* FUNC(void, RTE_CODE) Rte_COMCbk_SGMotorTemp_1281R (void) */

FUNC(void, RTE_CODE) Rte_COMCbk_SGMotorMode_1281R (void)
{
  uint8 Rte_InternalBuffer;

  Rte_ComHookRx_SGMotorMode_1281R();
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {
    if (Com_ReceiveSignal(ComConf_ComSignal_SGMotorMode_1281R, &Rte_InternalBuffer) == E_OK)
    {
      Rte_ComHook_SGMotorMode_1281R_SigRx(&Rte_InternalBuffer);
      Rte_ReceiveBuffer_4061E26959A98B41A8F9EF551DBA37CE_value = Rte_InternalBuffer;

      Rte_SetEvent_DRE_19B10114FE44DF3968D219DF6B46CFD0();

    }
  }

} /* FUNC(void, RTE_CODE) Rte_COMCbk_SGMotorMode_1281R (void) */

FUNC(void, RTE_CODE) Rte_COMCbk_SGChargerConnected_1281R (void)
{
  uint8 Rte_InternalBuffer;

  Rte_ComHookRx_SGChargerConnected_1281R();
  if (Rte_State == RTE_PARTITION_ACTIVE)
  {
    if (Com_ReceiveSignal(ComConf_ComSignal_SGChargerConnected_1281R, &Rte_InternalBuffer) == E_OK)
    {
      Rte_ComHook_SGChargerConnected_1281R_SigRx(&Rte_InternalBuffer);
      Rte_ReceiveBuffer_4061E26959A98B41A8F9EF551DBA37CE_value = Rte_InternalBuffer;

      Rte_SetEvent_DRE_19B10114FE44DF3968D219DF6B46CFD0();

    }
  }

} /* FUNC(void, RTE_CODE) Rte_COMCbk_SGChargerConnected_1281R (void) */

FUNC(Std_ReturnType, RTE_CODE) Rte_Start (void)
{
  Std_ReturnType Rte_Status = RTE_E_OK;

  if (Rte_State == RTE_PARTITION_UNINITIALIZED)
  {
    Rte_ModeDisablingDep_Type Rte_EnabledModeDisablingDep = {0U};

    Rte_State = RTE_PARTITION_STARTING;
    Rte_Common_Init();
    Rte_Task_Activate(Rte_Event_Task);
    if (ActivateTask(Rte_Event_Task) != E_OK)
    {
      Rte_Status = RTE_E_LIMIT;
    }
    /* Enable Mode Disabling Dependencies of the initial mode */
    Rte_EnableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
    /* Enable Mode Disabling Dependencies of the initial mode */
    Rte_EnableModeDisablingDep_0(Rte_EnabledModeDisablingDep);
    {
      Std_ReturnType Rte_QueueStatus = RTE_E_OK;
      uint8 Rte_Local_Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_head = Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.head;

      if (Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.tail == ((Rte_Local_Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_head + 1U) % 2U))
      {
        Rte_QueueStatus = RTE_E_LIMIT;
      }
      else
      {
        uint8 Rte_Local_Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_tailIdx = Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.tail % 1U;

        Atomics_ThreadFence();
        Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.queue[Rte_Local_Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB_tailIdx] = RTE_MODE_BswM_BSWM_BswMModeGroup_EB_INTGR_BSWM_STARTUP_TWO_A;
        Atomics_ThreadFence();
        Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.tail = ((Rte_ModeReceiveQueue_CB17E928A5383182DDEB81D870E37CAB.tail + 1U) % 2U);
      }
      if (Rte_QueueStatus != RTE_E_OK)
      {
        Rte_Status = RTE_E_LIMIT;
      }
      else
      {
        Rte_SetEvent_MSE_4FF9241E67DF8B0AADC83685D425BB32();

      }
    }
    if (Rte_StartScheduleTable_Rte_DefaultScheduleTable() != E_OK)
    {
      Rte_Status = RTE_E_LIMIT;
    }
    if (Rte_Status == RTE_E_OK)
    {
      Rte_State = RTE_PARTITION_ACTIVE;
    }
  }
  else
  {
    Rte_Status = RTE_E_LIMIT;
  }
  return Rte_Status;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Start (void) */

FUNC(Std_ReturnType, RTE_CODE) Rte_Stop (void)
{
  Std_ReturnType Rte_Status = RTE_E_OK;

  if (Rte_State == RTE_PARTITION_ACTIVE)
  {
    if (StopScheduleTable(Rte_DefaultScheduleTable) != E_OK)
    {
      Rte_Status = RTE_E_LIMIT;
    }
    Rte_Task_SetEvent(Rte_Event_Task, Rte_OSShutdownEvent);
    if (SetEvent(Rte_Event_Task, Rte_OSShutdownEvent) != E_OK)
    {
      Rte_Status = RTE_E_LIMIT;
    }
    if (Rte_Status == RTE_E_OK)
    {
      Rte_State = RTE_PARTITION_STOPPED;

    }
  }
  else
  {
    Rte_Status = RTE_E_LIMIT;
  }
  return Rte_Status;
} /* FUNC(Std_ReturnType, RTE_CODE) Rte_Stop (void) */

FUNC(void, RTE_CODE) SchM_Init (void)
{
  if ((SchM_State == SCHM_PARTITION_UNINITIALIZED) || (SchM_State == SCHM_PARTITION_STOPPED))
  {
    SchM_State = SCHM_PARTITION_STARTING;
    TS_MemBZero(Rte_ModeDisablingDep, sizeof(Rte_ModeDisablingDep_Type));
    (void)Rte_StartScheduleTable_SchM_DefaultScheduleTable();
    SchM_State = SCHM_PARTITION_ACTIVE;
  }

} /* FUNC(void, RTE_CODE) SchM_Init (void) */

FUNC(void, RTE_CODE) SchM_Deinit (void)
{
  if (SchM_State == SCHM_PARTITION_ACTIVE)
  {
    (void)StopScheduleTable(SchM_DefaultScheduleTable);
    SchM_State = SCHM_PARTITION_STOPPED;
  }

} /* FUNC(void, RTE_CODE) SchM_Deinit (void) */

#ifndef Rte_WaitGetClearEvent
FUNC(StatusType, RTE_CODE) Rte_WaitGetClearEvent (EventMaskType eventToWait, P2VAR(EventMaskType, AUTOMATIC, RTE_APPL_DATA) eventReceived, TaskType myTaskId)
{
  Rte_Task_WaitEvent(myTaskId, eventToWait);
  (void)WaitEvent(eventToWait);
  Rte_Task_WaitEventRet(myTaskId, eventToWait);
  (void)GetEvent(myTaskId, eventReceived);
  *eventReceived &= eventToWait;
  (void)ClearEvent(*eventReceived);
  return E_OK;
} /* FUNC(StatusType, RTE_CODE) Rte_WaitGetClearEvent (EventMaskType eventToWait, P2VAR(EventMaskType, AUTOMATIC, RTE_APPL_DATA) eventReceived, TaskType myTaskId) */

#endif

#define RTE_STOP_SEC_CODE
#include <Rte_MemMap.h>
/* ==================[Definition of functions with internal linkage]========== */
#define RTE_START_SEC_CODE
#include <Rte_MemMap.h>
STATIC FUNC(void, RTE_CODE) Rte_Common_Init (void)
{
  Rte_Irv_SWC_CyclicCounter_CurrentCounterValue = Init_Rte_Irv_SWC_CyclicCounter_CurrentCounterValue;
  Rte_ReceiveBuffer_4061E26959A98B41A8F9EF551DBA37CE_value = Init_Rte_ReceiveBuffer_4061E26959A98B41A8F9EF551DBA37CE_value;
  Rte_ModeVariable_CB17E928A5383182DDEB81D870E37CAB = Init_Rte_ModeVariable_CB17E928A5383182DDEB81D870E37CAB;

} /* STATIC FUNC(void, RTE_CODE) Rte_Common_Init (void) */

#define RTE_STOP_SEC_CODE
#include <Rte_MemMap.h>

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
